# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_pflexnetr_wrappers", use_symbols = TRUE, package_name = "pflexnetr")

#' @docType package
#' @usage NULL
#' @useDynLib pflexnetr, .registration = TRUE
NULL

pflexnet <- function(x, y, row_idx, alpha, kinship_covar, lambda_step_size, r) .Call(wrap__pflexnet, x, y, row_idx, alpha, kinship_covar, lambda_step_size, r)


# nolint end
